"""


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document:
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Self

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt


class PnLEntry(BaseModel):
    """
    PnLEntry
    """  # noqa: E501

    timestamp: StrictInt
    trade_pnl: StrictFloat | StrictInt
    trade_spot_pnl: StrictFloat | StrictInt
    inflow: StrictFloat | StrictInt
    outflow: StrictFloat | StrictInt
    spot_outflow: StrictFloat | StrictInt
    spot_inflow: StrictFloat | StrictInt
    pool_pnl: StrictFloat | StrictInt
    pool_inflow: StrictFloat | StrictInt
    pool_outflow: StrictFloat | StrictInt
    pool_total_shares: StrictFloat | StrictInt
    additional_properties: dict[str, Any] = {}
    __properties: ClassVar[list[str]] = [
        "timestamp",
        "trade_pnl",
        "trade_spot_pnl",
        "inflow",
        "outflow",
        "spot_outflow",
        "spot_inflow",
        "pool_pnl",
        "pool_inflow",
        "pool_outflow",
        "pool_total_shares",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of PnLEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of PnLEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "timestamp": obj.get("timestamp"),
                "trade_pnl": obj.get("trade_pnl"),
                "trade_spot_pnl": obj.get("trade_spot_pnl"),
                "inflow": obj.get("inflow"),
                "outflow": obj.get("outflow"),
                "spot_outflow": obj.get("spot_outflow"),
                "spot_inflow": obj.get("spot_inflow"),
                "pool_pnl": obj.get("pool_pnl"),
                "pool_inflow": obj.get("pool_inflow"),
                "pool_outflow": obj.get("pool_outflow"),
                "pool_total_shares": obj.get("pool_total_shares"),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
