"""


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document:
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Self

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr

from lighter.models.daily_return import DailyReturn
from lighter.models.share_price import SharePrice


class PublicPoolInfo(BaseModel):
    """
    PublicPoolInfo
    """  # noqa: E501

    status: StrictInt
    operator_fee: StrictStr
    min_operator_share_rate: StrictStr
    total_shares: StrictInt
    operator_shares: StrictInt
    annual_percentage_yield: StrictFloat | StrictInt
    sharpe_ratio: StrictFloat | StrictInt
    daily_returns: list[DailyReturn]
    share_prices: list[SharePrice]
    additional_properties: dict[str, Any] = {}
    __properties: ClassVar[list[str]] = [
        "status",
        "operator_fee",
        "min_operator_share_rate",
        "total_shares",
        "operator_shares",
        "annual_percentage_yield",
        "sharpe_ratio",
        "daily_returns",
        "share_prices",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of PublicPoolInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in daily_returns (list)
        _items = []
        if self.daily_returns:
            for _item in self.daily_returns:
                if _item:
                    _items.append(_item.to_dict())
            _dict["daily_returns"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in share_prices (list)
        _items = []
        if self.share_prices:
            for _item in self.share_prices:
                if _item:
                    _items.append(_item.to_dict())
            _dict["share_prices"] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of PublicPoolInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "status": obj.get("status"),
                "operator_fee": obj.get("operator_fee"),
                "min_operator_share_rate": obj.get("min_operator_share_rate"),
                "total_shares": obj.get("total_shares"),
                "operator_shares": obj.get("operator_shares"),
                "annual_percentage_yield": obj.get("annual_percentage_yield"),
                "sharpe_ratio": obj.get("sharpe_ratio"),
                "daily_returns": [DailyReturn.from_dict(_item) for _item in obj["daily_returns"]]
                if obj.get("daily_returns") is not None
                else None,
                "share_prices": [SharePrice.from_dict(_item) for _item in obj["share_prices"]]
                if obj.get("share_prices") is not None
                else None,
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
