"""


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document:
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Self

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr

from lighter.models.referral_point_entry import ReferralPointEntry


class ReferralPoints(BaseModel):
    """
    ReferralPoints
    """  # noqa: E501

    referrals: list[ReferralPointEntry]
    user_total_points: StrictFloat | StrictInt
    user_last_week_points: StrictFloat | StrictInt
    user_total_referral_reward_points: StrictFloat | StrictInt
    user_last_week_referral_reward_points: StrictFloat | StrictInt
    reward_point_multiplier: StrictStr
    additional_properties: dict[str, Any] = {}
    __properties: ClassVar[list[str]] = [
        "referrals",
        "user_total_points",
        "user_last_week_points",
        "user_total_referral_reward_points",
        "user_last_week_referral_reward_points",
        "reward_point_multiplier",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of ReferralPoints from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in referrals (list)
        _items = []
        if self.referrals:
            for _item in self.referrals:
                if _item:
                    _items.append(_item.to_dict())
            _dict["referrals"] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of ReferralPoints from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "referrals": [ReferralPointEntry.from_dict(_item) for _item in obj["referrals"]]
                if obj.get("referrals") is not None
                else None,
                "user_total_points": obj.get("user_total_points"),
                "user_last_week_points": obj.get("user_last_week_points"),
                "user_total_referral_reward_points": obj.get("user_total_referral_reward_points"),
                "user_last_week_referral_reward_points": obj.get("user_last_week_referral_reward_points"),
                "reward_point_multiplier": obj.get("reward_point_multiplier"),
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
