"""


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document:
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Annotated, Any, ClassVar, Self

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator


class ReqGetTrades(BaseModel):
    """
    ReqGetTrades
    """  # noqa: E501

    auth: StrictStr | None = None
    market_id: StrictInt | None = None
    account_index: StrictInt | None = -1
    order_index: StrictInt | None = None
    sort_by: StrictStr
    sort_dir: StrictStr | None = "desc"
    cursor: StrictStr | None = None
    var_from: StrictInt | None = Field(default=-1, alias="from")
    ask_filter: StrictInt | None = None
    role: StrictStr | None = "all"
    type: StrictStr | None = "all"
    limit: Annotated[int, Field(le=100, strict=True, ge=1)]
    aggregate: StrictBool | None = False
    additional_properties: dict[str, Any] = {}
    __properties: ClassVar[list[str]] = [
        "auth",
        "market_id",
        "account_index",
        "order_index",
        "sort_by",
        "sort_dir",
        "cursor",
        "from",
        "ask_filter",
        "role",
        "type",
        "limit",
        "aggregate",
    ]

    @field_validator("sort_by")
    def sort_by_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(["block_height", "timestamp", "trade_id"]):
            raise ValueError("must be one of enum values ('block_height', 'timestamp', 'trade_id')")
        return value

    @field_validator("sort_dir")
    def sort_dir_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["desc"]):
            raise ValueError("must be one of enum values ('desc')")
        return value

    @field_validator("role")
    def role_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["all", "maker", "taker"]):
            raise ValueError("must be one of enum values ('all', 'maker', 'taker')")
        return value

    @field_validator("type")
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["all", "trade", "liquidation", "deleverage", "market-settlement"]):
            raise ValueError(
                "must be one of enum values ('all', 'trade', 'liquidation', 'deleverage', 'market-settlement')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of ReqGetTrades from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: set[str] = set(
            [
                "additional_properties",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of ReqGetTrades from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "auth": obj.get("auth"),
                "market_id": obj.get("market_id"),
                "account_index": obj.get("account_index") if obj.get("account_index") is not None else -1,
                "order_index": obj.get("order_index"),
                "sort_by": obj.get("sort_by"),
                "sort_dir": obj.get("sort_dir") if obj.get("sort_dir") is not None else "desc",
                "cursor": obj.get("cursor"),
                "from": obj.get("from") if obj.get("from") is not None else -1,
                "ask_filter": obj.get("ask_filter"),
                "role": obj.get("role") if obj.get("role") is not None else "all",
                "type": obj.get("type") if obj.get("type") is not None else "all",
                "limit": obj.get("limit"),
                "aggregate": obj.get("aggregate") if obj.get("aggregate") is not None else False,
            }
        )
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj
